spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hunterhome?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
  servlet:
    context-path: /hunterhome

