spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hunterhome?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        min-idle: 0
        max-wait: -1ms
    timeout: 5000ms



server:
  port: 8080
  servlet:
    context-path: /hunterhome
  tomcat:
    uri-encoding: utf-8
logging:
  config: classpath:logback-spring.xml
  path: C:/log

